#!/bin/bash
set -Eeuo pipefail
set -x

# Fetch data using api call
node git_data_fetcher.mjs

# Change directory to build folder
cd build

pwd
# push to git
git add .
git commit -m "updated github api"
git push
